
language: java

jdk:
  - openjdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
    - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: irfana2003/Codecov_exp

          codecov: 
 token: 8895f9e5-d269-4c23-8ed4-15554835e7ac
